def findTheDifference(s, t):
        '''
        You are given two strings s and t.
        String t is generated by random shuffling string s and 
        then add one more letter at a random position.
        Return the letter that was added to t.

        Eg: Input: s = "abcd", t = "abcde"
            Output: "e"
            Explanation: 'e' is the letter that was added.
        
        '''
        S=list(s)
        S.sort()
        print(S)
        T=list(t)
        T.sort()
        print(T)
        for i in range(len(S)):
            if T[i]!=S[i]:
                return T[i]            
        return T[-1]
